//! `grit skill` — print an agent skill that explains how to use grit.

use anyhow::Result;
use serde::Serialize;

use crate::output::{HumanRender, MarkdownRender};

/// The skill text, with `{version}` replaced by the running grit's version.
const SKILL: &str = include_str!("skill.md");

/// Where agents conventionally look for a skill named `grit`.
const SUGGESTED_PATH: &str = ".agents/skills/grit/SKILL.md";

/// Result of `grit skill`.
#[derive(Serialize)]
pub struct SkillOutcome {
    /// The skill's name, from its front matter.
    pub name: String,
    /// The grit version the skill was generated by.
    pub version: String,
    /// A conventional place to save the skill, relative to a project root.
    pub path: String,
    /// The full `SKILL.md` text, front matter included.
    pub content: String,
}

impl HumanRender for SkillOutcome {
    fn render_human(&self) {
        // Exactly the file, so `grit skill > SKILL.md` works.
        print!("{}", self.content);
    }
}

impl MarkdownRender for SkillOutcome {
    fn render_markdown(&self) {
        // Same bytes as human mode so agents can save or parse the skill file.
        print!("{}", self.content);
    }
}

pub fn run() -> Result<SkillOutcome> {
    let version = env!("CARGO_PKG_VERSION");
    Ok(SkillOutcome {
        name: "grit".to_owned(),
        version: version.to_owned(),
        path: SUGGESTED_PATH.to_owned(),
        content: SKILL.replace("{version}", version),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skill_has_front_matter_and_version() {
        let outcome = run().unwrap();
        assert!(outcome
            .content
            .starts_with("---\nname: grit\ndescription: "));
        assert!(!outcome.content.contains("{version}"));
        assert!(outcome.content.contains(env!("CARGO_PKG_VERSION")));
    }

    /// Every `grit <command>` the skill mentions must exist, so the skill can't
    /// drift from the CLI when commands are renamed or removed.
    #[test]
    fn skill_mentions_only_real_commands() {
        use clap::CommandFactory;
        let cli = crate::Cli::command();
        let known: Vec<String> = cli
            .get_subcommands()
            .flat_map(|c| {
                std::iter::once(c.get_name().to_owned())
                    .chain(c.get_all_aliases().map(str::to_owned))
            })
            .collect();
        let mut missing = Vec::new();
        for (i, _) in SKILL.match_indices("`grit ") {
            let word: String = SKILL[i + 6..]
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '-')
                .collect();
            if !word.is_empty() && !known.contains(&word) {
                missing.push(word);
            }
        }
        assert!(
            missing.is_empty(),
            "unknown commands in skill.md: {missing:?}"
        );
    }
}
